language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - wget https://www.1c-bitrix.ru/download/start_encode_php5.tar.gz /tmp/start_encode_php5.tar.gz
  - tar -xvf /tmp/start_encode_php5.tar.gz
  - cd start_encode_php5
  - mkdir -p bitrix/components/eustatos/excomp
  - cd bitrix/components/eustatos/excomp
  - pwd

script:
  - composer dump-autoload -o
  - phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
