language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - wget https://www.1c-bitrix.ru/download/start_encode_php5.tar.gz -O /tmp/start_encode_php5.tar.gz
  - mkdir -p www/bitrix/components/eustatos/excomp
  - tar -xf /tmp/start_encode_php5.tar.gz -C www
  - mv eustatos/bitrix-boilerplate-component/ www/bitrix/components/eustatos/excomp/
  - cd www/bitrix/components/eustatos/excomp
  - pwd

cache:
  directories:
  - /tmp/start_encode_php5
before_cache:
  - rm -f /tmp/start_encode_php5/bitrix/components/eustatos/excomp
  
script:
  - composer dump-autoload -o
  - phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
