language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_install:
  - if [ ! -f $HOME/www/bitrix/modules/main/include/prolog_before.php ]; then
      wget https://www.1c-bitrix.ru/download/start_encode_php5.tar.gz -O /tmp/start_encode_php5.tar.gz;
      tar -xf /tmp/start_encode_php5.tar.gz -C $HOME/www;
    fi
  - mkdir -p $HOME/www/bitrix/components/eustatos/excomp
  - mv -f $TRAVIS_BUILD_DIR/* $HOME/www/bitrix/components/eustatos/excomp
  - cd $HOME/www/bitrix/components/eustatos/excomp
  - ls -la

cache:
  directories:
  - $HOME/www
before_cache:
  - rm -rf $HOME/bitrix/components/eustatos/excomp
  
script:
  - composer dump-autoload -o
  - phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
