language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_install:
  - wget https://www.1c-bitrix.ru/download/start_encode_php5.tar.gz -O /tmp/start_encode_php5.tar.gz
  - tar -xf /tmp/start_encode_php5.tar.gz -C $HOME
  - pwd

cache:
  directories:
  - $HOME
before_cache:
  - rm -f $HOME/bitrix/components/eustatos/excomp
  
script:
  - composer dump-autoload -o
  - phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
